fix the desktop file, and update the icon cache after installing icons

diff --git a/data/Makefile.am b/data/Makefile.am
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -8,6 +8,8 @@ desktop_DATA=$(desktop_in_files:.desktop.in.in=.desktop)
 @INTLTOOL_DESKTOP_RULE@
 
 hicolordir = $(datadir)/icons/hicolor
+gtk_update_icon_cache_bin = "$$((which gtk-update-icon-cache || echo /opt/gnome/bin/gtk-update-icon-cache)2>/dev/null)"
+gtk_update_icon_cache = $(gtk_update_icon_cache_bin) -f -t $(hicolordir)
 
 install-data-local:
 	$(mkinstalldirs) $(DESTDIR)$(hicolordir)/scalable/apps
@@ -16,7 +18,17 @@ install-data-local:
 	$(INSTALL_DATA) $(srcdir)/vmx-manager-48.png $(DESTDIR)$(hicolordir)/48x48/apps/vmx-manager.png
 	$(mkinstalldirs) $(DESTDIR)$(hicolordir)/24x24/apps
 	$(INSTALL_DATA) $(srcdir)/vmx-manager-24.png $(DESTDIR)$(hicolordir)/24x24/apps/vmx-manager.png
-
+	@-if test -z "$(DESTDIR)"; then \
+		if test -x $(gtk_update_icon_cache_bin); then \
+			echo "Updating GTK icon cache"; \
+			$(gtk_update_icon_cache); \
+		else \
+			echo "*** Icon cache not updated. Could not execute $(gtk_update_icon_cache_bin)"; \
+		fi \
+	else \
+		echo "*** Icon cache not updated. After install, run this:"; \
+		echo "***   $(gtk_update_icon_cache)"; \
+	fi
 
 EXTRA_DIST =				\
 	vmx-manager.glade		\
